### ISSUE TITLE
Error should contain meaningful information

### ISSUE THREAD

**Issue by Matt-Esch** [Raynos/jsonml-stringify#3]
Currently there is no error handling for invalid jsonml documents. Contextual error information (i.e. the offending structure) should be made clearly visible when invalid jsonml is passed.

**Comment by Raynos** [comment]
Pull request welcome :D

**Comment by Matt-Esch** [comment]
Invalid jsonml currently yields errors like:

``` sh
/home/matt/source/spells-demo-app/node_modules/jsonml-stringify/unpack-selector.js:6
    var selectorMatches = selector.split(splitSelectorRegex)
                                   ^
TypeError: Cannot call method 'split' of undefined
    at unpackSelector (/home/matt/source/spells-demo-app/node_modules/jsonml-stringify/unpack-selector.js:6:36)
    at stringify (/home/matt/source/spells-demo-app/node_modules/jsonml-stringify/index.js:55:19)
    at /home/matt/source/spells-demo-app/node_modules/jsonml-stringify/index.js:73:26
    at Array.forEach (native)
    at renderChildren (/home/matt/source/spells-demo-app/node_modules/jsonml-stringify/index.js:72:18)
    at stringify (/home/matt/source/spells-demo-app/node_modules/jsonml-stringify/index.js:46:9)
    at /home/matt/source/spells-demo-app/node_modules/jsonml-stringify/index.js:73:26
    at Array.forEach (native)
    at renderChildren (/home/matt/source/spells-demo-app/node_modules/jsonml-stringify/index.js:72:18)
    at stringify (/home/matt/source/spells-demo-app/node_modules/jsonml-stringify/index.js:62:9)
```

**Comment by Raynos** [comment]
Also

``` sh

/home/raynos/Documents/colingo-web/node_modules/colingo-session/node_modules/redis/index.js:535
            throw err;
                  ^
TypeError: Cannot read property '0' of undefined
    at normalize (/home/raynos/Documents/colingo-web/node_modules/jsonml-stringify/normalize.js:17:31)
    at stringify (/home/raynos/Documents/colingo-web/node_modules/jsonml-stringify/index.js:18:14)
    at /home/raynos/Documents/colingo-web/node_modules/jsonml-stringify/index.js:64:26
    at Array.forEach (native)
    at renderChildren (/home/raynos/Documents/colingo-web/node_modules/jsonml-stringify/index.js:63:18)
    at stringify (/home/raynos/Documents/colingo-web/node_modules/jsonml-stringify/index.js:48:9)
    at /home/raynos/Documents/colingo-web/node_modules/jsonml-stringify/index.js:64:26
    at Array.forEach (native)
    at renderChildren (/home/raynos/Documents/colingo-web/node_modules/jsonml-stringify/index.js:63:18)
    at stringify (/home/raynos/Documents/colingo-web/node_modules/jsonml-stringify/index.js:48:9)
9 Jul 18:29:52 - [nodemon] app crashed - waiting for file changes before starting...
```

This one happens if you do `[ undefined ]`

**Comment by Matt-Esch** [comment]
```
/home/matt/repos/colingo-web/node_modules/jsonml-stringify/attrs.js:6
    var attrString = Object.keys(attributes).map(function (key) {
                            ^
TypeError: Object.keys called on non-object
    at Function.keys (native)
    at attrs (/home/matt/repos/colingo-web/node_modules/jsonml-stringify/attrs.js:6:29)
    at stringify (/home/matt/repos/colingo-web/node_modules/jsonml-stringify/index.js:40:48)
    at /home/matt/repos/colingo-web/node_modules/jsonml-stringify/index.js:72:24
    at Array.forEach (native)
    at renderChildren (/home/matt/repos/colingo-web/node_modules/jsonml-stringify/index.js:66:18)
    at stringify (/home/matt/repos/colingo-web/node_modules/jsonml-stringify/index.js:51:9)
    at /home/matt/repos/colingo-web/node_modules/jsonml-stringify/index.js:72:24
    at Array.forEach (native)
    at renderChildren (/home/matt/repos/colingo-web/node_modules/jsonml-stringify/index.js:66:18)
```

Second argument text node, third argument array of child nodes

**Comment by Raynos** [comment]
usage:

``` js
["div.counter", {
  "data-marker": "unreadCounter." + s._id,
  "display": unreadCount === 0 ? "none" : "block"
}, unreadCount]
```

Error:

```
/home/raynos/Documents/colingo-web/node_modules/redis/index.js:551
            throw err;
                  ^
TypeError: Object 2 has no method 'filter'
    at normalize (/home/raynos/Documents/colingo-web/node_modules/jsonml-stringify/normalize.js:34:33)
    at stringify (/home/raynos/Documents/colingo-web/node_modules/jsonml-stringify/index.js:19:14)
    at /home/raynos/Documents/colingo-web/node_modules/jsonml-stringify/index.js:81:24
    at Array.forEach (native)
    at renderChildren (/home/raynos/Documents/colingo-web/node_modules/jsonml-stringify/index.js:75:18)
    at stringify (/home/raynos/Documents/colingo-web/node_modules/jsonml-stringify/index.js:60:9)
    at /home/raynos/Documents/colingo-web/node_modules/jsonml-stringify/index.js:81:24
    at Array.forEach (native)
    at renderChildren (/home/raynos/Documents/colingo-web/node_modules/jsonml-stringify/index.js:75:18)
    at stringify (/home/raynos/Documents/colingo-web/node_modules/jsonml-stringify/index.js:60:9)
```

fix:

When passing a number as the third argument we should throw a loud exception that "Number is not a child. probably want string"
