### ISSUE TITLE
empty array error

### ISSUE THREAD

**Issue by robertjd** [Raynos/jsonml-stringify#5]
when returning an empty array:

```
Error: Invalid JSONML data structure [ undefined, {}, [] ] Selector is not a string
    at normalize (/Users/robert/thing/thing-web/node_modules/jsonml-stringify/normalize.js:40:15)
    at stringify (/Users/robert/thing/thing-web/node_modules/jsonml-stringify/index.js:19:14)
    at /Users/robert/thing/thing-web/node_modules/jsonml-stringify/index.js:81:24
    at Array.forEach (native)
    at renderChildren (/Users/robert/thing/thing-web/node_modules/js
```

**Comment by Raynos** [comment]
Fixed in 0.3.22
